# Generated by Django 4.2.8 on 2023-12-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_contact_customercontact_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adddress 2'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zipcode'),
        ),
    ]
