# Generated by Django 3.2.23 on 2023-12-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customercontact_address1_customercontact_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(max_length=100, unique=True, verbose_name='Workorder')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Budget')),
                ('quoted_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quoted Price')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customercontact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
