# Generated by Django 3.2.23 on 2024-01-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customercontact_address1_customercontact_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(max_length=100, unique=True, verbose_name='Workorder')),
                ('internal_company', models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], max_length=100, verbose_name='Internal Company')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Budget')),
                ('quoted_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quoted Price')),
                ('original_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Order')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customercontact')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkorderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Unit Price')),
                ('mark_up', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Markup')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Price')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.category')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('item_order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display Order')),
                ('original_item_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Order')),
                ('original_item_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Price')),
                ('internal_company', models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], max_length=100, verbose_name='Internal Company')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.category')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder')),
            ],
        ),
    ]
