# Generated by Django 3.2.23 on 2024-01-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderitem',
            name='mark_up',
        ),
    ]
