# Generated by Django 3.2.23 on 2023-12-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_auto_20231229_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
