# Generated by Django 3.2.23 on 2024-01-04 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_auto_20240104_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='design_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.designtype'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Unit Price'),
        ),
    ]
