# Generated by Django 3.2.23 on 2024-01-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_auto_20240104_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='design_type',
            field=models.BooleanField(blank=True, null=True, verbose_name='Design Type'),
        ),
    ]
