# Generated by Django 3.2.23 on 2023-12-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_auto_20231229_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='internal_company',
            field=models.CharField(default='none', max_length=100, verbose_name='Internal Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='original_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Order'),
        ),
    ]
