# Generated by Django 3.2.23 on 2024-01-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_category_design_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
    ]
