# Generated by Django 3.2.23 on 2023-12-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_auto_20231229_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='description',
            field=models.CharField(default='None', max_length=100, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], max_length=100, verbose_name='Internal Company'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], max_length=100, verbose_name='Internal Company'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.category'),
        ),
    ]
