# Generated by Django 3.2.23 on 2023-12-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_auto_20231229_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='WorkorderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('quantity', models.CharField(max_length=100, verbose_name='Description')),
                ('unit_price', models.CharField(max_length=100, verbose_name='Description')),
                ('total_price', models.CharField(max_length=100, verbose_name='Description')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.category')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder')),
            ],
        ),
    ]
